[workspace]
resolver = "2"
exclude = [
  "third_party/wind-ui-rust",
]
members = [
  "rust/windows-common-core",
  "rust/tsf-support-core",
  "rust/launcher-core",
  "rust/package-core",
  "rust/release-pqc-signer",
  "rust/control-core",
  "rust/process-execution-core",
  "rust/register-core",
  "rust/config-qa",
  "rust/config-core",
  "rust/config-poc",
  "rust/candidate-core",
  "rust/tsf-poc",
  "rust/protocol-core",
  "rust/engine-core",
  "rust/measurement-core",
  "rust/mock-engine-core",
]

[profile.dev]
opt-level = 0
debug = "line-tables-only"
codegen-units = 16
lto = false
incremental = true

[profile.dev.package."*"]
debug = false

[profile.test]
opt-level = 0
debug = "line-tables-only"
codegen-units = 16
lto = false
incremental = true

[profile.debugging]
inherits = "dev"
debug = true
