[package]
name = "fcitx5-tsf-poc"
version = "0.1.0"
edition = "2021"
license = "LGPL-2.1-or-later"
publish = false

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
fcitx5-protocol-core = { path = "../protocol-core" }
fcitx5-windows-common-core = { path = "../windows-common-core" }
windows = { version = "0.62.2", features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_Com",
  "Win32_System_LibraryLoader",
  "Win32_System_Ole",
  "Win32_System_Registry",
  "Win32_System_Variant",
  "Win32_Graphics_Gdi",
  "Win32_UI_HiDpi",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_TextServices",
  "Win32_UI_WindowsAndMessaging",
] }
windows-core = "0.62.2"
