[package]
name = "fcitx5-tsf-poc"
version = "0.1.0"
edition = "2021"
license = "LGPL-2.1-or-later"
publish = false

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
windows = { version = "0.62.2", features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_Com",
  "Win32_System_LibraryLoader",
  "Win32_System_Registry",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_TextServices",
] }
windows-core = "0.62.2"
