[package]
name = "fcitx5-control-core"
version = "0.1.0"
edition = "2021"
license = "LGPL-2.1-or-later"
publish = false

[lib]
path = "src/lib.rs"
crate-type = ["rlib", "staticlib"]

[[bin]]
name = "fcitx5-control"
path = "src/main.rs"

[dependencies]
toml_edit = { version = "0.22.27", default-features = false, features = ["display", "parse"] }
fcitx5-config-core = { path = "../config-core" }
