[package]
name = "fcitx5-package-core"
version = "0.1.0"
edition = "2021"
license = "LGPL-2.1-or-later"
publish = false

[lib]
path = "src/lib.rs"
crate-type = ["rlib", "staticlib"]

[[bin]]
name = "fcitx5-package-core"
path = "src/main.rs"

[[bin]]
name = "fcitx5-provider"
path = "src/provider_main.rs"

[[bin]]
name = "fcitx5-downloader"
path = "src/downloader_main.rs"

[[bin]]
name = "fcitx5-updater"
path = "src/updater_main.rs"

[[bin]]
name = "fcitx5-deployer"
path = "src/deployer_main.rs"

[[bin]]
name = "fcitx5-bootstrap"
path = "src/bootstrap_main.rs"

[dependencies]
blake3 = { version = "=1.5.5", default-features = false, features = ["pure"] }

[build-dependencies]
cc = "=1.4.4"
