[package]
name = "fcitx5-config-poc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fcitx5-config-poc"
path = "src/main.rs"

[[bin]]
name = "fcitx5-config-rust"
path = "src/bin/fcitx5_config_rust.rs"

[dependencies]
fcitx5-candidate-core = { path = "../candidate-core" }
fcitx5-control-core = { path = "../control-core" }
fcitx5-package-core = { path = "../package-core" }
